#!/usr/bin/env python3
"""
Export bible_common.py (single source of truth) → bible_meta.js for bible.html.

Run after any BIBLE_DATA / BOOK_NAMES change:
  python export_bible_meta.py

Deploy bible_meta.js together with bible.html.
"""

from __future__ import annotations

import json
from pathlib import Path

from bible_common import ALL_BOOKS, BIBLE_DATA, BOOK_NAMES, NT_BOOKS

OUT = Path(__file__).resolve().parent / "bible_meta.js"


def main():
    # BIBLE_DATA values are chapter→verse-count lists (same shape as old VERSE_COUNTS)
    verse_counts = {code: list(counts) for code, counts in BIBLE_DATA.items()}
    book_names = dict(BOOK_NAMES)
    book_order = list(ALL_BOOKS)
    nt_books = list(NT_BOOKS)

    payload = {
        "verseCounts": verse_counts,
        "bookNames": book_names,
        "bookOrder": book_order,
        "ntBooks": nt_books,
        "source": "apps/365DBR/bible_common.py",
    }

    # Validate ROM TR counts are present (sanity)
    rom = verse_counts.get("ROM") or []
    if len(rom) < 16 or rom[13] != 23 or rom[15] != 27:
        raise SystemExit(
            f"[export_bible_meta] Unexpected ROM chapter lengths {rom[-3:]} — "
            f"expected ch14=23, ch16=27 (TR). Check bible_common.BIBLE_DATA."
        )

    js = (
        "/* AUTO-GENERATED by export_bible_meta.py from bible_common.py — do not edit by hand */\n"
        "window.__BIBLE_META__ = "
        + json.dumps(payload, ensure_ascii=False, separators=(",", ":"))
        + ";\n"
    )
    OUT.write_text(js, encoding="utf-8")
    print(f"Wrote {OUT} ({OUT.stat().st_size} bytes)")
    print(f"  books={len(book_order)} ROM ch14={rom[13]} ch16={rom[15]}")


if __name__ == "__main__":
    main()
