"""January is generated by generate_readings.py (full year, one write)."""
from generate_readings import main

if __name__ == "__main__":
    print("generate_january.py now runs the full-year generator (January + Feb–Dec).")
    main()
